<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="V-DEV0242" name="TestScripts.TC019_Reassaign_Claim_SingleCalim" tests="1" failures="0" timestamp="10 Oct 2017 09:50:34 GMT" time="1.415" errors="1">
  <testcase name="tc018" time="1.415" classname="TestScripts.TC019_Reassaign_Claim_SingleCalim">
    <error type="com.hp.lft.sdk.GeneralLeanFtException" message="An Internal problem has occurred, please make sure the LeanFT sdk was properly initialized.">
      <![CDATA[com.hp.lft.sdk.GeneralLeanFtException: An Internal problem has occurred, please make sure the LeanFT sdk was properly initialized.
	at com.hp.lft.sdk.internal.CommunicationClientImpl.send(CommunicationClientImpl.java:76)
	at com.hp.lft.sdk.web.BrowserFactory$BrowserFactoryInstance$4.invoke(BrowserFactory.java:181)
	at com.hp.lft.sdk.web.BrowserFactory$BrowserFactoryInstance$4.invoke(BrowserFactory.java:170)
	at com.hp.lft.sdk.internal.TestObjectOperationWrapper.executeWithEvents(TestObjectOperationWrapper.java:120)
	at com.hp.lft.sdk.web.BrowserFactory$BrowserFactoryInstance.getAllOpenBrowsers(BrowserFactory.java:204)
	at com.hp.lft.sdk.web.BrowserFactory.getAllOpenBrowsers(BrowserFactory.java:79)
	at TestScripts.TC019_Reassaign_Claim_SingleCalim.tc018(TC019_Reassaign_Claim_SingleCalim.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- tc018 -->
</testsuite> <!-- TestScripts.TC019_Reassaign_Claim_SingleCalim -->
